apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-api-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-api-exporter
  template:
    metadata:
      labels:
        name: kube-api-exporter
    spec:
      containers:
      - name: kube-api-exporter
        image: tomwilkie/kube-api-exporter
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
